llm:
  api_url: "http://localhost:11434/api/generate"
  model: "llama3"
  temperature: 0.2

prompt_template: |
  Gere um teste unitário em Java usando JUnit5.
  A classe alvo é {{ class_name }}.
  Método: {{ method_name }} (linha {{ line }}).
  Mutação: {{ mutator }}.
  Descrição: {{ description }}.
  Código fonte:
  {{ source_code }}

  Crie um teste que revele a mutação.
